
platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'TokenCore_Example' do
  
  pod 'TokenCore', :path => '../'
  pod 'PureLayout'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Alamofire', '~> 5.6.1'
  pod 'GRKOpenSSLFramework', '1.0.2.20.2', :modular_headers => true
  pod 'BigInt', git: "https://github.com/attaswift/BigInt.git"
  pod 'CoreBitcoin', git: "https://github.com/sunimp/CoreBitcoin.git", :tag => "0.6.9"
  pod 'libscrypt', git: "https://github.com/sunimp/libscrypt.git", :tag => "v1.22.1"

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end
